export const ADD_PLACE = 'FETCH_MECHANICS'
export const FETCHING_COIN_DATA_SUCCESS = "FETCH_MECHANICS_SUCCESS";
export const FETCHING_COIN_DATA_FAIL = "FETCH_MECHANICS_FAIL";
export const FETCHING_COIN_DATA_FAIL = "OPEN_MECHANICS_CARDS";
export const FETCHING_COIN_DATA_FAIL = "OPEN_CARDS_DETAIL";
export const FETCHING_COIN_DATA = "FETCH_MECHANICS_SEARCH";
export const FETCHING_COIN_DATA = "FETCH_MECHANICS_SEARCH_SUCCESS";
export const FETCHING_COIN_DATA = "FETCH_MECHANICS_SEARCH_FAIL";